### ISSUE TITLE
Docker Spy crushes when using crane and fig

### ISSUE THREAD

**Issue by mikeys** [iverberk/docker-spy#3]
Hey there,

I'm running the `docker_spy` container using the following command:
`docker run -e="DNS_DOMAIN=localdomain" -d --name docker_spy -p 53:53/udp -p 53:53 -v /var/run/docker.sock:/var/run/docker.sock iverberk/docker-spy`

I'm using crane to bring up a mongo container (from the official docker image) with the following crane.yml

```yml
---
containers:
  mongo:
    image: mongo:2.6
    run: 
      hostname: mongo.localdomain
```

Looking at the docker_spy logs with `docker logs -f docker_spy`

This is what I see:

```bash

panic: runtime error: slice bounds out of range

goroutine 25 [running]:
runtime.panic(0x7c6f00, 0xa2e6cf)
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/panic.c:279 +0xf5
main.(*Spy).mutateContainerInCache(0xc2080003b0, 0xc2080ac3b4, 0x9, 0xc2080ac3b0, 0x4)
        /Users/Ivo/Projects/Go/src/github.com/iverberk/docker-spy/spy.go:45 +0x168
main.(*Spy).readEventStream(0xc2080003b0, 0xc2080044e0)
        /Users/Ivo/Projects/Go/src/github.com/iverberk/docker-spy/spy.go:37 +0x96
created by main.(*Spy).Watch
        /Users/Ivo/Projects/Go/src/github.com/iverberk/docker-spy/spy.go:22 +0x7d

goroutine 16 [chan receive]:
main.main()
        /Users/Ivo/Projects/Go/src/github.com/iverberk/docker-spy/main.go:67 +0x5b6

goroutine 19 [finalizer wait]:
runtime.park(0x416800, 0xa32740, 0xa30969)
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xa32740, 0xa30969)
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall]:
os/signal.loop()
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 21 [syscall]:
syscall.Syscall(0x2f, 0x5, 0x7fd7cbee2a40, 0x0, 0x7cca20, 0x1, 0x5d66c5)
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/syscall/asm_linux_amd64.s:21 +0x5
syscall.recvmsg(0x5, 0x7fd7cbee2a40, 0x0, 0xc208038340, 0x0, 0x0)
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/syscall/zsyscall_linux_amd64.go:1902 +0x56
syscall.Recvmsg(0x5, 0xc208052000, 0x200, 0x200, 0xc208021290, 0x28, 0x28, 0x0, 0x806ee0, 0x0, ...)
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/syscall/syscall_linux.go:517 +0x193
net.(*netFD).readMsg(0xc2080263f0, 0xc208052000, 0x200, 0x200, 0xc208021290, 0x28, 0x28, 0x0, 0x0, 0x0, ...)
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/net/fd_unix.go:292 +0x37e
net.(*UDPConn).ReadMsgUDP(0xc20803a038, 0xc208052000, 0x200, 0x200, 0xc208021290, 0x28, 0x28, 0x1, 0x42798a, 0x70b820, ...)
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/net/udpsock_posix.go:96 +0x18a
github.com/miekg/dns.readFromSessionUDP(0xc20803a038, 0xc208052000, 0x200, 0x200, 0x200, 0x200, 0x0, 0x0)
        /Users/Ivo/Projects/Go/src/github.com/miekg/dns/udp.go:44 +0xcb
github.com/miekg/dns.(*Server).readUDP(0xc208024680, 0xc20803a038, 0x77359400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/Ivo/Projects/Go/src/github.com/miekg/dns/server.go:530 +0x15b
github.com/miekg/dns.(*Server).serveUDP(0xc208024680, 0xc20803a038, 0x0, 0x0)
        /Users/Ivo/Projects/Go/src/github.com/miekg/dns/server.go:411 +0x102
github.com/miekg/dns.(*Server).ListenAndServe(0xc208024680, 0x0, 0x0)
        /Users/Ivo/Projects/Go/src/github.com/miekg/dns/server.go:274 +0x63e
main.func·001()
        /Users/Ivo/Projects/Go/src/github.com/iverberk/docker-spy/dns.go:44 +0xdb
created by main.(*DNS).Run
        /Users/Ivo/Projects/Go/src/github.com/iverberk/docker-spy/dns.go:48 +0x3b4

goroutine 22 [IO wait]:
net.runtime_pollWait(0x7fd7cc06e740, 0x72, 0x0)
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc2080264c0, 0x72, 0x0, 0x0)
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc2080264c0, 0x0, 0x0)
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).accept(0xc208026460, 0x8d5f88, 0x0, 0x7fd7cc06d4b0, 0xb)
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/net/fd_unix.go:419 +0x343
net.(*TCPListener).AcceptTCP(0xc20803a060, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/net/tcpsock_posix.go:234 +0x5d
github.com/miekg/dns.(*Server).serveTCP(0xc208024750, 0xc20803a060, 0x0, 0x0)
        /Users/Ivo/Projects/Go/src/github.com/miekg/dns/server.go:380 +0xe0
github.com/miekg/dns.(*Server).ListenAndServe(0xc208024750, 0x0, 0x0)
        /Users/Ivo/Projects/Go/src/github.com/miekg/dns/server.go:261 +0x37f
main.func·002()
        /Users/Ivo/Projects/Go/src/github.com/iverberk/docker-spy/dns.go:53 +0xdb
created by main.(*DNS).Run
        /Users/Ivo/Projects/Go/src/github.com/iverberk/docker-spy/dns.go:57 +0x3ea

goroutine 24 [select]:
github.com/fsouza/go-dockerclient.(*eventMonitoringState).monitorEvents(0xc2080260e0, 0xc20804c080)
        /Users/Ivo/Projects/Go/src/github.com/fsouza/go-dockerclient/event.go:175 +0x380
created by github.com/fsouza/go-dockerclient.(*eventMonitoringState).enableEventMonitoring
        /Users/Ivo/Projects/Go/src/github.com/fsouza/go-dockerclient/event.go:148 +0x113

goroutine 26 [IO wait]:
net.runtime_pollWait(0x7fd7cc06e8a0, 0x72, 0x0)
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc208027090, 0x72, 0x0, 0x0)
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc208027090, 0x0, 0x0)
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).Read(0xc208027030, 0xc20805f000, 0x1000, 0x1000, 0x0, 0x7fd7cc06d4b0, 0xb)
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/net/fd_unix.go:242 +0x34c
net.(*conn).Read(0xc20803a098, 0xc20805f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/net/net.go:122 +0xe7
bufio.(*Reader).fill(0xc208004840)
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/bufio/bufio.go:97 +0x1b3
bufio.(*Reader).ReadSlice(0xc208004840, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/bufio/bufio.go:298 +0x22c
net/http.readLine(0xc208004840, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/net/http/chunked.go:111 +0x59
net/http.(*chunkedReader).beginChunk(0xc208021e60)
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/net/http/chunked.go:48 +0x45
net/http.(*chunkedReader).Read(0xc208021e60, 0xc208052600, 0x200, 0x200, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/net/http/chunked.go:78 +0xc0
net/http.(*body).readLocked(0xc208038840, 0xc208052600, 0x200, 0x200, 0x5, 0x0, 0x0)
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/net/http/transfer.go:577 +0x81
net/http.(*body).Read(0xc208038840, 0xc208052600, 0x200, 0x200, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/net/http/transfer.go:572 +0x11a
encoding/json.(*Decoder).readValue(0xc208029040, 0x75, 0x0, 0x0)
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/encoding/json/stream.go:124 +0x557
encoding/json.(*Decoder).Decode(0xc208029040, 0x6ed3e0, 0xc2080bbd40, 0x0, 0x0)
        /usr/local/Cellar/go/1.3.3/libexec/src/pkg/encoding/json/stream.go:44 +0x7a
github.com/fsouza/go-dockerclient.func·004(0xc20804a3f0, 0xc20803c210)
        /Users/Ivo/Projects/Go/src/github.com/fsouza/go-dockerclient/event.go:289 +0x18b
created by github.com/fsouza/go-dockerclient.(*Client).eventHijack
        /Users/Ivo/Projects/Go/src/github.com/fsouza/go-dockerclient/event.go:307 +0x4a6

```

I've previously used fig instead of crane and everything worked smoothly, although after a while, the server crashed with the same error... it seems to me like a bug of some sort...

Would like to hear your input about this...

**Comment by iverberk** [comment]
Hi, thanks for reporting this. I will take a look at it tonight and let you know what I can find.

**Comment by mikeys** [comment]
Might've saved you some time, PR @ https://github.com/iverberk/docker-spy/pull/4/files

**Comment by iverberk** [comment]
I just committed the fix. It as a simple fix so I didn't change the pull request. Thanks for making the effort though and I hope you keep enjoying docker-spy :-)

I also updated the image on the Docker registry.
